name: Publish Kobweb artifacts

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      # See: https://docs.gradle.org/current/userguide/signing_plugin.html#sec:in-memory-keys
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.VARABYTE_SIGNING_KEY }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Add secret Gradle properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.VARABYTE_GRADLE_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: Publish Kobweb artifacts
        run: ./gradlew publish --scan
